main/urls.py
from django.urls import path

from main.views import IndexView, TaskCreateView, TagsView, TagsCreateView, task_done, TaskUpdateView, TaskDeleteView, \
    TagsUpdateView, TagsDeleteView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("task/create/", TaskCreateView.as_view(), name="create-task"),
    path("tags/", TagsView.as_view(), name="tags-view"),
    path("tags/create/", TagsCreateView.as_view(), name="tags-create"),
    path("tags/update/<int:pk>", TagsUpdateView.as_view(), name="tags-update"),
    path("tags/delete/<int:pk>", TagsDeleteView.as_view(), name="tags-delete"),
    path("task/done/<int:pk>", task_done, name="task-done"),
    path("task/update/<int:pk>", TaskUpdateView.as_view(), name="task-update"),
    path("task/delete/<int:pk>", TaskDeleteView.as_view(), name="task-delete"),
]

app_name = "todo"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="todo")),
]

main/models.py
from django.db import models


class Task(models.Model):
    name = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateField(null=True, blank=True)
    is_done = models.BooleanField()
    tags = models.ManyToManyField("Tags", related_name="tasks")


class Tags(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

main/forms.py
from django import forms

from main.models import Task


class TaskUpdateForm(forms.ModelForm):
    deadline = forms.DateField(
        label="Deadline",
        required=False,
        widget=forms.widgets.DateInput(
            format="%Y-%m-%d",
            attrs={"class": "form-control", "type": "date"}
        )
    )

    class Meta:
        model = Task
        fields = "__all__"

main/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from main.forms import TaskUpdateForm
from main.models import Task, Tags


class IndexView(generic.ListView):
    model = Task
    context_object_name = "tasks"
    template_name = "main/index.html"


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskUpdateForm
    success_url = reverse_lazy("todo:index")


def task_done(request, pk):
    task = Task.objects.get(id=pk)

    task.is_done = not task.is_done
    task.save()

    return HttpResponseRedirect(reverse_lazy("todo:index"))


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskUpdateForm
    success_url = reverse_lazy("todo:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "main/task_delete_confirm.html"
    success_url = reverse_lazy("todo:index")


class TagsView(generic.ListView):
    model = Tags
    context_object_name = "tags"
    template_name = "main/tags.html"


class TagsCreateView(generic.CreateView):
    model = Tags
    fields = "__all__"
    success_url = reverse_lazy("todo:tags-view")


class TagsUpdateView(generic.UpdateView):
    model = Tags
    fields = "__all__"
    success_url = reverse_lazy("todo:tags-view")


class TagsDeleteView(generic.DeleteView):
    model = Tags
    template_name = "main/tag_delete_confirm.html"
    success_url = reverse_lazy("todo:tags-view")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Taxi Service</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tags-view' %}">Tags</a></li>
</ul>

templates/main/index.html
{% extends "base.html" %}

{% block title %}
  <title>ToDo List</title>
{% endblock %}

{% block content %}
  <h1>TODO list
    <a href="{% url 'todo:create-task' %}" class="btn btn-primary link-to-page">Add task</a></h1>
  <ul>
    {% for task in tasks %}
      <li>
        <strong>{{ task.name }}
          {% if task.is_done %}
            <span style="color: green">Done</span>
            <a href="{% url 'todo:task-done' pk=task.id %}" class="btn btn-success link-to-page">Complete</a></h1>
          {% else %}
            <span style="color: red">Not done</span>
            <a href="{% url 'todo:task-done' pk=task.id %}" class="btn btn-secondary link-to-page">Undo</a></h1>
          {% endif %}
        </strong>
      </li>
      <li>Created: {{ task.created }} {% if task.deadline %}
        <span style="color: saddlebrown">Deadline: {{ task.deadline }}{% endif %}</span></li>
      <li>Tags:{% for tag in task.tags.all %} {{ tag }}{% endfor %}
        <a href="{% url 'todo:task-update' pk=task.id %}">Update</a>
        <a href="{% url 'todo:task-delete' pk=task.id%}">Delete</a>
      </li>
      <hr class="horizontal gray-light">
    {% endfor %}
  </ul>
{% endblock %}

templates/main/tag_delete_confirm.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo:tags-view' %}" class="btn btn-secondary">No</a>
  </form>
{% endblock %}

templates/main/tags.html
{% extends "base.html" %}

{% block title %}
  <title>Tags</title>
{% endblock %}

{% block content %}
  <h1>Tags
  <a href="{% url 'todo:tags-create' %}" class="btn btn-primary link-to-page">Add tag</a></h1>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
    {% for tag in tags %}
      <tr>
        <td>{{ tag.name }}</td>
        <td><a href="{% url 'todo:tags-update' pk=tag.id %}" class="btn btn-secondary">Update</a></td>
        <td><a href="{% url 'todo:tags-delete' pk=tag.id %}" class="btn btn-secondary">Delete</a></td>
      </tr>
    {% endfor %}
  </table>

{% endblock %}

templates/main/tags_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/main/task_delete_confirm.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo:index' %}" class="btn btn-secondary">No</a>
  </form>
{% endblock %}

templates/main/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}